import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./_Components/Footer/Footer";
import Navbar_  from "./_Components/Navbar/Navbar";

import '@fortawesome/fontawesome-free/css/all.min.css'
import { Toaster } from "sonner";
import SessionProviderHandler from "./_Components/SessionProviderHandler/SessionProviderHandler";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <SessionProviderHandler>
          <Navbar_ />
          {children}
          <Toaster />
          <Footer />
        </SessionProviderHandler>
      </body>
    </html>
  );
}
